Repository Strategienavigator/Strategienavigator-frontend, pull requests merged in 2023-11, with the labels that each got.

#94 Feature/persona changes
  package-lock.json
  package.json
  src/components/tools/persona-analysis/PersonaAnalysis.tsx
  src/components/tools/persona-analysis/export/PersonaPDFExporter.tsx
  src/components/tools/persona-analysis/matrix/PersonaAnalysisInfoShower.tsx
  src/components/tools/persona-analysis/persona-analysis.scss
  src/components/tools/persona-analysis/steps/PersonaInfo/PersonaInfo.ts
  src/components/tools/persona-analysis/steps/PersonaInfo/PersonaInfoComponent-ti.ts
  src/components/tools/persona-analysis/steps/PersonaInfo/PersonaInfoComponent.tsx
  src/components/tools/persona-analysis/steps/PersonaPersonality/PersonaPersonality.ts
  src/components/tools/persona-analysis/steps/PersonaPersonality/PersonaPersonalityComponent-ti.ts
  src/components/tools/persona-analysis/steps/PersonaPersonality/PersonaPersonalityComponent.tsx
  src/components/tools/persona-analysis/steps/PersonaSummary/PersonaInfoItem.tsx
  src/components/tools/persona-analysis/steps/PersonaSummary/PersonaSummaryComponent.tsx
  src/components/tools/test-analysis/extraWindow/TestSubstepsExtraWindow.tsx
  src/components/tools/test-analysis/steps/TestSubsteps/TestSubsteps.ts
  src/components/tools/test-analysis/steps/TestSubsteps/TestSubstepsComponent.tsx
  src/general-components/CardComponent/CardComponent.tsx
  src/general-components/CardComponent/CardComponentWithName.tsx
  src/general-components/Export/ExcelExporter.tsx
  src/general-components/Export/Exporter.ts
  src/general-components/Export/JSONExporter.tsx
  src/general-components/Export/PDF/PDFExporter.tsx
  src/general-components/Export/PDF/PDFExporterPreview.tsx
  src/general-components/Export/PDFExporter.tsx
  src/general-components/Messages/Messages.tsx
  src/general-components/Tool/SteppableTool/StepComponent/StepComponent.tsx
Labels: enhancement, Tool

#96 changed toolbox db name to strategienavigator
  cypress/e2e/tool_tests/swot-analysis_I.cy.js
  cypress/e2e/tool_tests/swot-analysis_II.cy.js
  cypress/e2e/tool_tests/swot-analysis_III.cy.js
  cypress/e2e/validation/profile.cy.js
  cypress/e2e/validation/registration.cy.js
  cypress/support/e2e.js
Labels: bug

#95 Feature/resource export
  src/components/tools/test-analysis/TestAnalysis-ti.ts
  src/components/tools/test-analysis/import/TestAnalysisJSONImporter.ts
  src/components/tools/test-analysis/steps/TestCardcomponent/TestCardcomponentComponent-ti.ts
  src/components/tools/test-analysis/steps/TestComparecomponent/TestComparecomponentComponent-ti.ts
  src/components/tools/test-analysis/steps/TestCoordinateSystem/TestCoordinateSystemComponent-ti.ts
  src/components/tools/test-analysis/steps/TestResources/TestResources.ts
  src/components/tools/test-analysis/steps/TestResources/TestResourcesComponent-ti.ts
  src/components/tools/test-analysis/steps/TestResources/TestResourcesComponent.tsx
  src/components/tools/test-analysis/steps/TestSubsteps/TestSubstepsComponent-ti.ts
  src/general-components/API/calls/SaveResources.tsx
  src/general-components/API/calls/Saves.tsx
  src/general-components/Datastructures.tsx
  src/general-components/Export/JSONExporter.tsx
  src/general-components/Import/JSONImporter.tsx
  src/general-components/Tool/Home/Import/ImportModal.tsx
  src/general-components/Tool/Tool.tsx
  src/general-components/Tool/ToolSavePage/ToolSavePage.tsx
Labels: enhancement
